apiVersion: v1
kind: Service
metadata:
  name: chatterbox-user-service
spec:
  selector:
    app: chatterbox-user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
